### ISSUE TITLE
Contact information sharing thread

### ISSUE THREAD

**Issue by aaomidi** [StateFarmInsCodingCompetition/2016-StateFarm-CodingCompetitionProblem#28]
email: amir@aaomidi.com
telegram: https://telegram.me/aaomidi
steam: aaomidi
facebook: fb.com/amir.a.omidi
battle.net: aaomidi#1537 (pro genji)

**Comment by arxenix** [comment]
email: me@ankursundara.com
facebook: http://fb.com/ankur.sundara
