### ISSUE TITLE
Language Discrepancy (Original Title: Tests are wrong?)

### ISSUE THREAD

**Issue by Vilsol** [StateFarmInsCodingCompetition/2016-StateFarm-CodingCompetitionProblem#8]
Hello, it appears that the challenge is a bit more challenging than it should be.

If you would please look at the screenshot provided below, which is a formatted version of the data that one of the tests is compared against, you can see there are 3 languages: English, Spanish and German.

![](http://i.imgur.com/RX8Zww9.png)

Now, if you compare that to the file of Mary Contreras, you will notice, that she indeed knows those languages, but they are written in the language of that language.

![](http://i.imgur.com/t0PkWMd.png)

Are we actually supposed to map each name for a language from English to the native language equivalent?

**Comment by Clete2** [comment]
This is as designed. In the problem statement explanation, we call out that the correct language text is in the `title` attribute of the `div` tag rather than the `text()` of the `div` tag.
